main: com.shadow2hel.shadbed.ShadBed
name: ShadBed
version: 1.1.2
api-version: 1.14
author: Shadow2hel
description: An improved plugin for sleep voting.
commands:
  sb:
    description: Show what percentage of players you need to skip the night.
    usage: /sb
    permission: ShadBed.sb
    permission-message: You don't have the ShadBed.sb permission.
  sbchange:
    description: Change settings of ShadBed.
    usage: |
      /<command> <sleepmessage|skipmessage|leavemessage> <message> - Change the message when someone goes to bed.

      Supports placeholders such as %player% (player who's going to sleep), %sleepers% (amount of %sleepers%) and
      %total% (total amount of players online).

      Example: /<command> sleepmessage %player% is sleeping [%sleepers%/%total%] - will show for example:
      Shadow2hel is sleeping [1/5].
    permission: ShadBed.sb.change
    permission-message: You don't have the ShadBed.sb.change permission.
